### ISSUE TITLE
Please help,

### ISSUE THREAD

**Issue by saad21212121** [afkapp/bombcrypto-bcbot#20]
Please help, I am facing problems when running the bot, please help me

My telegram id is @baka_baji

It shows me the following error ....

Error: config.yaml file not found, rename EXAMPLE-config.yaml to config.yaml inside /config folder
Erro: Arquivo config.yaml não encontrado, renomear EXAMPLE-config.yaml para config.yaml dentro da pasta /config
Starting the bot with loop execution...

**Comment by afkapp** [comment]
Hello,

Open source don't have free support for installation.

Read and execute:

Error: config.yaml file not found, rename EXAMPLE-config.yaml to config.yaml inside /config folder
