### ISSUE TITLE
Decode error while running bot / Erro de Decode ao rodar o bot.

### ISSUE THREAD

**Issue by mgramelich** [afkapp/bombcrypto-bcbot#4]
If you get a message like this one:
![image](https://user-images.githubusercontent.com/49958344/147494498-d31d87ec-145c-4668-aa7f-8703a7ace6ac.png)

Just change both lines below on **INDEX.PY** or **INDEX-MA-WINDOWS.PY**:

`with open("./config/config.yaml", 'r') as s:`
to 
`with open("./config/config.yaml", 'r', encoding="utf8") as s:`

**AND**

`stream = open("./config/telegram.yaml", 'r')`
to
`stream = open("./config/telegram.yaml", 'r', encoding="utf8")`

**Comment by afkapp** [comment]
Thanks, fixed.
